repos: 
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-ast 
  - id: debug-statements
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    args: [--ignore-missing-imports]
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.64.0'
  hooks:
  - id: terraform_fmt
