name: CI
on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  format-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: black
        uses: psf/black@stable
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: terraform
  deploy_terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
    - id: 'get_tfavrs'
      name: 'get tfvars file from secret manager'
      run: |
        gcloud secrets versions access latest --secret=config_tfavrs --project=${{ secrets.GCP_PROJECT_ID }} > config.tfvars
        gcloud secrets versions access latest --secret=terraform_tfavrs --project=${{ secrets.GCP_PROJECT_ID }} > terraform.tfvars
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - id: 'init'
      name: 'terraform init'
      run: |
        terraform init -backend-config=config.tfvars
    - id: 'plan'
      name: 'terraform plan'
      run: terraform plan
    - id: 'apply'
      name: 'terraform apply'
      run: terraform apply
      if: github.ref == 'refs/heads/main'
